" Enable line numbers
set number

" Show filename on status line
set ls=2
set statusline+=%F

" Ignore case for searches UNLESS I use caps
set ignorecase
set scs

" Display whitespace
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" Enable auto-indentation
set autoindent

" Tab width
set tabstop=4
set shiftwidth=4

" File type specific
"	Python
autocmd Filetype python setlocal expandtab
"	C/C++
autocmd Filetype c,cpp,cc,h,hpp,hh setlocal noexpandtab
